//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Dept_EF.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Student_Department_DBEntities : DbContext
    {
        public Student_Department_DBEntities()
            : base("name=Student_Department_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept_Table> Dept_Table { get; set; }
        public virtual DbSet<Student_Table> Student_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
