//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Dept_EF.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Table
    {
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Email { get; set; }
        public int Foreign_Dept_Id { get; set; }
    
        public virtual Dept_Table Dept_Table { get; set; }
    }
}
