//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_Id { get; set; }
        public int Restaurant_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public string FoodItems { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string Destination { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
