//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDeptApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int S_id { get; set; }
        public string S_name { get; set; }
        public string S_cgpa { get; set; }
        public int Dept_id { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
