//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecoveryTestEntities1 : DbContext
    {
        public RecoveryTestEntities1()
            : base("name=RecoveryTestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enroll> Enrolls { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public object Enroll { get; internal set; }
    }
}
